### ISSUE TITLE
Issues with some dates

### ISSUE THREAD

**Issue by i-arun-samui** [kentang2017/kinliuren#3]
Hi,

Can you have a look with 
jieqi 雨水
daygangzhi 癸卯
hourgangzhi 己未

jieqi 雨水
daygangzhi 癸卯
hourgangzhi 庚申

jieqi 處暑
daygangzhi 癸卯
hourgangzhi 癸丑

jieqi 冬至
daygangzhi 癸卯
hourgangzhi 辛酉

jieqi 芒種
daygangzhi 癸卯
hourgangzhi 丙辰

for me it returns ['不適用，或試他法', '不適用，或試他法', '不適用，或試他法', '不適用，或試他法', '不適用，或試他法', '不適用，或試他法', '不適用，或試他法', '不適用，或試他法']

Thank you !

**Comment by kentang2017** [comment]
fixed. please update and try again

**Comment by i-arun-samui** [comment]
Thanks for answering,

I check but it brings much more issues now with zeike() returning None
ex :
jieqi : 小寒
daygangzhi 甲寅
hourgangzhi 丙寅

**Comment by kentang2017** [comment]
fixed and thanks for report the bugs

**Comment by i-arun-samui** [comment]
Hi,
Thanks seems working perfectly now.

Could you if possible write a simple HTML code to present the results ?

thanks again !

**Comment by kentang2017** [comment]
> Hi,
> Thanks seems working perfectly now.
> 
> Could you if possible write a simple HTML code to present the results ?
> 
> thanks again !

sorry, this is not provided.

**Comment by i-arun-samui** [comment]
Thanks,

I did noticed very well it wasn't provided, that is why I have asked if you could add it.
