### ISSUE TITLE
请问：涉害的方式是哪种？

### ISSUE THREAD

**Issue by Juan-hwt** [kentang2017/kinliuren#5]
我使用大六壬手机版，大部分的课式都对的上，但是发现涉害课 有的就对不上了，请教一下这个的计算方法

**Comment by kentang2017** [comment]
您好，或者可否直接列舉有關例子？我的那個涉害是根據幾個方式找出來的，由於涉害也算是前期編寫出來，可能有少許漏洞，因此，若然有直接的例子，我可以做更徹底的修正，謝謝。

**Comment by Juan-hwt** [comment]
程序得到的是 卯亥未
app给到如下：
![d71a4f43f903967e1dad32c778befed](https://user-images.githubusercontent.com/82884966/172366053-1da603e5-6146-4f6f-8a02-e4de7dbfb9ef.jpg)

**Comment by kentang2017** [comment]
已修正。

**Comment by Juan-hwt** [comment]
谢谢，我回去再测试下

**Comment by Juan-hwt** [comment]
0.1.2.3版本
t = kinliuren.Liuren('小寒', '丁丑', '己酉', '庚午').result(0)
print(t)

![mmexport1655043804294](https://user-images.githubusercontent.com/82884966/173237859-73e27bb0-72bb-4cb1-ae58-0f13d775a7b2.png)

**Comment by kentang2017** [comment]
please update and try again

**Comment by kentang2017** [comment]
i updated it to 1.2.4 already.

**Comment by Juan-hwt** [comment]
> i updated it to 1.2.4 already.

ok  everything is running
